name: PR Check

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04
    container: python:3.7-slim

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_PASSWORD: ''
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
#      - name: Set up Python 3.7
#        uses: actions/setup-python@v2
#        with:
#          python-version: 3.7
      - name: Setup env
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
          bash setup_env.sh
      - name: Lint
        run: |
          bash lint.sh
      - name: Test
        run: |
          bash test.sh
        env:
          POSTGRES_HOST: postgres
